### ISSUE TITLE
How to relax restriction on collision between links?

### ISSUE THREAD

**Issue by RyanJiao** [dexsuite/dex-retargeting#9]
Hi, I was trying the leap hand urdf in the dex-urdf repository. And I manually add an fingertip link like this：
``` <link name="RF_touchtip" />
  <joint name="RF_fixtip" type="fixed">
      <parent link="fingertip_3" />
      <child link="RF_touchtip" />
      <origin rpy="0.0 -1.57079633 0.0" xyz="-0.01 -0.04 0.01 " />
  </joint>
```
And this is the yaml I used:
```
retargeting:
  type: vector
  urdf_path: yzqin_leap_hand/leap_hand_right.urdf
  wrist_link_name: "base"

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: null
  target_origin_link_names: [ "base", "base", "base", "base" ]
  target_task_link_names: [ "TH_touchtip", "FF_touchtip", "MF_touchtip", "RF_touchtip" ]
  scaling_factor: 1.4

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [ [ 0, 0, 0, 0 ], [ 4, 8, 12, 16 ] ]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2
```
The pose seems to be alright, but when I try to grasp something, the gap between fingertips looks too huge. I add a video to show the problem. And I' like to ask how to relax restriction on collision between links?
https://github.com/dexsuite/dex-retargeting/assets/56286149/7441fd18-96b5-4d9e-a037-2e25b9d4e0cc
